### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by amirouche** [arew-scheme/arew-scheme#1]
- [x] review untangle
- [x] review termbox bindings
- [ ] srfi 167 with sqlite backend
- [ ] srfi 168 with sqlite backend
