### ISSUE TITLE
v0.3.0

### ISSUE THREAD

**Issue by amirouche** [arew-scheme/arew-scheme#21]
- [x] Make it possible to compile `arew.scm` #22 
- [x] Using `arew eval program.scm ...` pass `...` to the eval'ed program #22 
- [ ] Look into wrong line / col numbers in errors
- [x] `demo/bibendum` #20 
- [ ] documentation quickfix #14 
- [x] arew petite requirement #24 
- [ ] make it possible to configure optimization during compilation

**Comment by amirouche** [comment]
> Look into wrong line / col numbers in errors

I think it is linked to the fact that `arew.scm` will rely on multiple calls to `eval`

**Comment by amirouche** [comment]
It was released. See https://github.com/arew-scheme/arew-scheme/releases/tag/v0.3.0
